import { useEffect, useState } from 'react';
import { Instagram, Trash2, RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Account={id:string;platform:string;username:string;account_id:string;token_expires_at:string|null};
export function Accounts(){
 const [items,setItems]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Faça login novamente.');const r=await fetch('/api/social-accounts',{headers:{Authorization:`Bearer ${session.access_token}`}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');setItems(j.accounts||[])}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const connect=async(kind:'instagram'|'facebook')=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session)return setError('Faça login novamente.');const r=await fetch(`/api/auth/${kind}/start`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao iniciar conexão');window.location.href=j.url;}catch(e){setError(e instanceof Error?e.message:'Falha ao conectar.')}};
 const remove=async(id:string)=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;await fetch(`/api/social-accounts?id=${encodeURIComponent(id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${session.access_token}`}});load()};
 return <div className="space-y-6"><div><p className="text-sm text-white/45">Contas</p><h1 className="text-3xl font-black">Redes conectadas</h1></div><div className="glass rounded-3xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-bold">Instagram e Facebook</div><p className="text-sm text-white/45">Conecte suas contas usando os fluxos oficiais da Meta.</p></div><div className="flex gap-2"><button onClick={load} className="btn btn-secondary"><RefreshCw size={16}/></button><button onClick={()=>connect('instagram')} className="btn btn-primary"><Instagram size={16}/> <span className="ml-2">Instagram</span></button><button onClick={()=>connect('facebook')} className="btn btn-secondary">Facebook</button></div></div>{error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}<div className="mt-6 space-y-3">{loading?<div className="text-white/50">Carregando…</div>:items.length===0?<div className="rounded-2xl border border-white/10 p-6 text-center text-white/50">Nenhuma conta conectada.</div>:items.map(a=><div key={a.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.03] p-4"><div><div className="font-semibold">@{a.username||a.account_id}</div><div className="text-xs text-white/40">{a.platform === 'facebook' ? 'Facebook' : 'Instagram'}</div></div><button onClick={()=>remove(a.id)} className="rounded-xl p-2 text-red-300 hover:bg-red-500/10"><Trash2 size={18}/></button></div>)}</div></div></div>
}
