import { useEffect, useMemo, useState } from 'react';
import { Upload, Sparkles, Save, ArrowLeft } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { generateAICaption } from '../lib/ai';
import type { Project, Video, PresetConfig } from '../lib/types';
import { defaultPreset } from '../lib/types';

export function Editor({ project, video, onDone }: { project: Project; video?: Video; onDone: () => void }) {
 const [cfg,setCfg]=useState<PresetConfig>(defaultPreset); const [saving,setSaving]=useState(false); const [generating,setGenerating]=useState(false); const [previewUrl,setPreviewUrl]=useState(''); const [msg,setMsg]=useState(''); const set=(k:keyof PresetConfig,v:unknown)=>setCfg(c=>({...c,[k]:v} as PresetConfig));
 useEffect(()=>{let cancelled=false;(async()=>{const {data}=await supabase.from('presets').select('*').eq('project_id',project.id).eq('name','Padrão principal').maybeSingle();if(!cancelled&&data?.config)setCfg({...defaultPreset,...data.config} as PresetConfig);if(video?.storage_path){const {data:s}=await supabase.storage.from('videos').createSignedUrl(video.storage_path,3600);if(!cancelled&&s?.signedUrl)setPreviewUrl(s.signedUrl);}})();return()=>{cancelled=true}},[project.id,video?.id]);
 const update=(k:keyof PresetConfig,v:unknown)=>set(k,v);
 const handleIA=async()=>{setGenerating(true);setMsg('');try{const topic=video?.original_name||project.name;const text=await generateAICaption(`Escreva uma legenda em português para um Reel sobre "${topic}". Seja natural, curta, envolvente, com CTA e 5 hashtags relevantes. Não invente fatos.`);update('caption',text);setMsg('Legenda gerada.');}catch(e){setMsg(e instanceof Error?e.message:'Falha no Gemini.');}finally{setGenerating(false)}};
 const save=async()=>{setSaving(true);setMsg('');const {error}=await supabase.from('presets').upsert({project_id:project.id,name:'Padrão principal',config:cfg},{onConflict:'project_id,name'});if(!error&&video){await supabase.from('videos').update({caption:cfg.caption}).eq('id',video.id);}setSaving(false);if(error)setMsg(error.message);else setMsg('Padrão salvo.');};
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={onDone} className="mb-2 inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft size={15}/> Biblioteca</button><p className="text-sm text-white/45">Editor de padrão</p><h1 className="text-3xl font-black">{video?.original_name||project.name}</h1></div><button onClick={save} className="btn btn-primary"><Save size={16}/><span className="ml-2">{saving?'Salvando…':'Salvar padrão'}</span></button></div>
  {msg&&<div className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white/70">{msg}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
   <div className="glass rounded-3xl p-5"><div className="mx-auto aspect-[9/16] max-w-[420px] overflow-hidden rounded-3xl bg-black relative">{previewUrl?<video key={previewUrl} src={previewUrl} controls className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center text-center text-white/35 p-8"><div><div className="text-6xl mb-3">🎬</div>Envie um vídeo para visualizar o original.</div></div>}{cfg.titleEnabled&&<div className="pointer-events-none absolute left-5 right-5 top-8 text-center font-black drop-shadow-[0_2px_6px_rgba(0,0,0,.9)]" style={{fontSize:Math.max(18,cfg.titleSize/2)}}>{cfg.title||'Seu título'}</div>}{cfg.footerEnabled&&<div className="pointer-events-none absolute bottom-8 left-5 right-5 text-center text-sm font-semibold drop-shadow-[0_2px_6px_rgba(0,0,0,.9)]">{cfg.footer||'Seu texto inferior'}</div>}{cfg.overlayPath&&<div className="pointer-events-none absolute" style={{left:`${cfg.overlayX*100}%`,top:`${cfg.overlayY*100}%`,opacity:cfg.overlayOpacity,transform:'translate(-50%,-50%)',width:`${cfg.overlayScale*100}%`}}><img src={cfg.overlayPath} className="w-full"/></div>}</div></div>
   <div className="glass rounded-3xl p-5 space-y-6 max-h-[78vh] overflow-auto">
    <Section title="Enquadramento"><select value={cfg.aspectRatio} onChange={e=>update('aspectRatio',e.target.value)} className="field"><option>9:16</option><option>1:1</option><option>16:9</option></select><Field label={`Zoom ${cfg.zoom.toFixed(2)}x`}><input type="range" min="1" max="2" step=".01" value={cfg.zoom} onChange={e=>update('zoom',+e.target.value)}/></Field></Section>
    <Section title="Bordas"><label className="check"><input type="checkbox" checked={cfg.borderEnabled} onChange={e=>update('borderEnabled',e.target.checked)}/> Ativar borda</label><Field label={`${cfg.borderWidth}px`}><input type="range" min="0" max="40" value={cfg.borderWidth} onChange={e=>update('borderWidth',+e.target.value)}/></Field><input type="color" value={cfg.borderColor} onChange={e=>update('borderColor',e.target.value)} className="h-10 w-full rounded-xl bg-white/5"/></Section>
    <Section title="Título"><label className="check"><input type="checkbox" checked={cfg.titleEnabled} onChange={e=>update('titleEnabled',e.target.checked)}/> Ativar</label><input value={cfg.title} onChange={e=>update('title',e.target.value)} placeholder="Título fixo" className="field"/><Field label={`Tamanho ${cfg.titleSize}px`}><input type="range" min="18" max="90" value={cfg.titleSize} onChange={e=>update('titleSize',+e.target.value)}/></Field></Section>
    <Section title="Inferior"><label className="check"><input type="checkbox" checked={cfg.footerEnabled} onChange={e=>update('footerEnabled',e.target.checked)}/> Ativar</label><input value={cfg.footer} onChange={e=>update('footer',e.target.value)} placeholder="Texto inferior" className="field"/></Section>
    <Section title="Legenda"><div className="flex items-center justify-between gap-2"><span className="text-xs text-white/40">Texto do post</span><button onClick={handleIA} disabled={generating} className="btn btn-secondary text-xs"><Sparkles size={14}/><span className="ml-2">{generating?'Gerando…':'Gerar com Gemini'}</span></button></div><textarea value={cfg.caption} onChange={e=>update('caption',e.target.value)} rows={6} placeholder="Legenda" className="field resize-none"/></Section>
    <Section title="Overlay / Logo"><label className="btn btn-secondary w-full cursor-pointer"><Upload size={15}/><span className="ml-2">Enviar PNG</span><input type="file" accept="image/png,image/webp,image/jpeg" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const path=`${user.id}/${project.id}/overlay-${crypto.randomUUID()}-${f.name}`;const up=await supabase.storage.from('videos').upload(path,f,{upsert:true});if(up.error){setMsg(up.error.message);return;}const {data:s}=await supabase.storage.from('videos').createSignedUrl(path,3600);update('overlayPath',s?.signedUrl||'');setMsg('Overlay carregado para visualização.');}}/></label><Field label={`Opacidade ${Math.round(cfg.overlayOpacity*100)}%`}><input type="range" min="0" max="1" step=".01" value={cfg.overlayOpacity} onChange={e=>update('overlayOpacity',+e.target.value)}/></Field><Field label={`Escala ${Math.round(cfg.overlayScale*100)}%`}><input type="range" min=".05" max=".7" step=".01" value={cfg.overlayScale} onChange={e=>update('overlayScale',+e.target.value)}/></Field><Field label={`Horizontal ${Math.round(cfg.overlayX*100)}%`}><input type="range" min="0" max="1" step=".01" value={cfg.overlayX} onChange={e=>update('overlayX',+e.target.value)}/></Field><Field label={`Vertical ${Math.round(cfg.overlayY*100)}%`}><input type="range" min="0" max="1" step=".01" value={cfg.overlayY} onChange={e=>update('overlayY',+e.target.value)}/></Field></Section>
   </div>
  </div>
 </div>
}
function Section({title,children}:{title:string;children:any}){return <section><h2 className="mb-3 text-sm font-bold text-white/70">{title}</h2><div className="space-y-3">{children}</div></section>}
function Field({label,children}:{label:string;children:any}){return <label className="block"><div className="mb-1 text-xs text-white/40">{label}</div>{children}</label>}
