import { useEffect, useMemo, useState } from 'react';
import { Trash2, CheckSquare, Square, Edit3, Play, Download } from 'lucide-react';
import { supabase } from '../lib/supabase';
import type { Project, Video } from '../lib/types';
export function Library({project,onBack,onEdit}:{project:Project;onBack:()=>void;onEdit:(v?:Video)=>void}){
 const [files,setFiles]=useState<Video[]>([]); const [busy,setBusy]=useState(false); const [q,setQ]=useState(''); const [selected,setSelected]=useState<string[]>([]); const load=async()=>{const {data}=await supabase.from('videos').select('*').eq('project_id',project.id).order('sort_order');setFiles((data||[]) as Video[]);setSelected([])}; useEffect(()=>{load()},[project.id]); const shown=useMemo(()=>files.filter(v=>v.original_name.toLowerCase().includes(q.toLowerCase())),[files,q]);
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const chosen=Array.from(e.target.files||[]);if(!chosen.length)return;const oversized=chosen.filter(f=>f.size>50*1024*1024);if(oversized.length){alert(`O limite do plano gratuito do Supabase é 50 MB por arquivo.\n\n${oversized.map(f=>f.name).join('\n')}`);return;}setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return;}for(let i=0;i<chosen.length;i++){const f=chosen[i];const path=`${user.id}/${project.id}/${crypto.randomUUID()}-${f.name}`;const up=await supabase.storage.from('videos').upload(path,f,{upsert:false});if(!up.error)await supabase.from('videos').insert({project_id:project.id,user_id:user.id,original_name:f.name,storage_path:path,size_bytes:f.size,status:'uploaded',sort_order:files.length+i});}setBusy(false);await load()};
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); const all=shown.length>0&&shown.every(v=>selected.includes(v.id)); const toggleAll=()=>setSelected(all?selected.filter(id=>!shown.some(v=>v.id===id)):[...new Set([...selected,...shown.map(v=>v.id)])]);
 const remove=async(ids:string[])=>{if(!ids.length||!confirm(`Excluir ${ids.length} vídeo(s)? Essa ação não pode ser desfeita.`))return;setBusy(true);for(const id of ids){const v=files.find(x=>x.id===id);if(v){await supabase.storage.from('videos').remove([v.storage_path,...(v.render_path?[v.render_path]:[]),...(v.thumbnail_path?[v.thumbnail_path]:[])]);}await supabase.from('processing_jobs').delete().eq('video_id',id);await supabase.from('videos').delete().eq('id',id);}setBusy(false);await load()};
 const queue=async()=>{const ids=selected.length?selected:shown.map(v=>v.id);if(!ids.length)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('videos').update({status:'queued'}).in('id',ids);const {data:existing}=await supabase.from('processing_jobs').select('video_id').in('video_id',ids).in('status',['pending','processing']);const blocked=new Set((existing||[]).map(x=>x.video_id));const jobs=ids.filter(id=>!blocked.has(id)).map(video_id=>({user_id:user.id,project_id:project.id,video_id,status:'pending'}));if(jobs.length)await supabase.from('processing_jobs').insert(jobs);await load()};
 const download=async(v:Video)=>{const path=v.render_path||v.storage_path;const {data,error}=await supabase.storage.from('videos').createSignedUrl(path,3600);if(error||!data?.signedUrl){alert(error?.message||'Não foi possível gerar o link.');return;}window.open(data.signedUrl,'_blank')};
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={onBack} className="text-sm text-white/45 hover:text-white">← Projetos</button><h1 className="mt-1 text-3xl font-black">{project.name}</h1><p className="text-white/45">{files.length} vídeos</p></div><div className="flex flex-wrap gap-2"><label className="btn btn-secondary cursor-pointer">{busy?'Processando…':'Importar vídeos'}<input type="file" accept="video/*" multiple className="hidden" onChange={upload}/></label><button onClick={queue} className="btn btn-primary">Processar {selected.length?'selecionados':'lote'}</button><button onClick={()=>remove(selected)} disabled={!selected.length||busy} className="btn btn-secondary text-red-300 disabled:opacity-30"><Trash2 size={16}/><span className="ml-2">Excluir</span></button></div></div>
 <div className="flex flex-wrap items-center gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome…" className="field max-w-md"/><button onClick={toggleAll} className="btn btn-secondary">{all?<CheckSquare size={16}/>:<Square size={16}/>}<span className="ml-2">{all?'Desmarcar':'Selecionar todos'}</span></button>{selected.length>0&&<span className="text-sm text-white/50">{selected.length} selecionado(s)</span>}</div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{shown.map(v=><div key={v.id} className={`glass overflow-hidden rounded-2xl ${selected.includes(v.id)?'ring-2 ring-violet-400/60':''}`}><div className="relative aspect-[9/14] bg-black"><button onClick={()=>toggle(v.id)} className="absolute left-3 top-3 z-10 rounded-xl bg-black/60 p-2">{selected.includes(v.id)?<CheckSquare size={18}/>:<Square size={18}/>}</button>{v.render_path?<button onClick={()=>download(v)} className="absolute right-3 top-3 z-10 rounded-xl bg-black/60 p-2"><Download size={17}/></button>:<Play size={36} className="absolute inset-0 m-auto text-white/30"/>}</div><div className="p-4"><div className="truncate font-semibold" title={v.original_name}>{v.original_name}</div><div className="mt-1 text-xs text-white/40">{(v.size_bytes/1048576).toFixed(1)} MB · {v.status}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>onEdit(v)} className="rounded-xl bg-white/5 py-2 text-sm hover:bg-white/10"><Edit3 size={14} className="inline mr-1"/>Editar</button><button onClick={()=>remove([v.id])} className="rounded-xl bg-red-500/10 py-2 text-sm text-red-200 hover:bg-red-500/20"><Trash2 size={14} className="inline mr-1"/>Excluir</button></div></div></div>)}</div>{shown.length===0&&<div className="glass rounded-2xl p-10 text-center text-white/50">Nada encontrado.</div>}</div>
}
